# Generated by Django 2.2.1 on 2019-05-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
