# Generated by Django 2.2.1 on 2019-05-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
