# Generated by Django 2.2.1 on 2019-05-16 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='contents',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='others',
        ),
    ]
