# Generated by Django 2.2.1 on 2019-05-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn10',
            field=models.CharField(default='', max_length=10),
        ),
    ]
